- name: Install dependencies for ckan
  apt:
    pkg:
      - libpq5
      - redis-server
      - nginx
      - supervisor
    state: present
    update_cache: yes

- name: Download ckan release
  get_url:
    dest: /root/
    url: http://packaging.ckan.org/python-ckan_2.9-bionic_amd64.deb

- name: Install ckan release
  apt:
    deb: /root/python-ckan_2.9-bionic_amd64.deb
    state: present

- name: Install dependencies for postgres setup
  apt:
    pkg:
      - postgresql
      - python3-psycopg2
      - python-psycopg2

# TODO: configure & secure secrets
- name: Create postgres user
  no_log: true
  become: true
  become_user: postgres
  postgresql_user:
    name: ckan_default
    password: password123
    state: present

- name: Create postgres database
  postgresql_db:
    owner: ckan_default
    name: ckan_default
    encoding: utf-8
  become: true
  become_user: postgres

- name: Install ckan config
  template:
    src: ./ckan.ini.j2
    dest: /etc/ckan/default/ckan.ini

- name: Install solr-tomcat
  apt:
    name: solr-tomcat
    state: present

- name: Install tomcat config
  template:
    src: ./tomcat.xml.j2
    dest: /etc/tomcat9/server.xml

- name: Symlink solr schema
  file:
    state: link
    force: yes
    path: /etc/solr/conf/schema.xml
    src: /usr/lib/ckan/default/src/ckan/ckan/config/solr/schema.xml

- name: Restart tomcat
  systemd:
    name: tomcat9
    state: restarted

# TODO: figure out why python2.7 is used
- apt:
    name: libpython2.7
    state: present

# TODO: make idempotent
- name: Initialize ckan database
  command: ckan db init

# TODO: make idempotent
- name: Reload supervisord tasks
  command: supervisorctl reload

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
